#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_index:
  path: /
  controller: App\Controller\HomeController::index

app_playlists:
  path: /playlists
  controller: App\Controller\UserController::playlists

app_playlists_tracks_cards:
  path: /playlists/tracks/cards/{playlist_id}/{page}
  controller: App\Controller\UserController::playlistTracksCards
  requirements:
    playlistId: '\w+'
    page: '\d+'

app_playlists_tracks_table:
  path: /playlists/tracks/table/{playlist_id}/{page}
  controller: App\Controller\UserController::playlistTracksTable
  requirements:
    playlistId: '\w+'
    page: '\d+'

app_login:
  path: /login
  controller: App\Controller\AuthController::login

app_menu:
  path: /menu
  controller: App\Controller\UserController::menu